### ISSUE TITLE
css selectors

### ISSUE THREAD

**Issue by rgylling** [tmzelaya/portfolio#8]
In your javascript I think it would be better to use advanced css selectors rather than using classes and ID's to select your elements.
lines 7 and 8 view js contain ID's

**Comment by tmzelaya** [comment]
Not doing.

The classes/IDs were already in place by the time I got to Tuesday's assignment. It made less sense to unnecessarily use advanced selectors that to take advantage of the classes and IDs I had already assigned for styling purposes.
