### ISSUE TITLE
sections

### ISSUE THREAD

**Issue by rgylling** [tmzelaya/portfolio#9]
I think it would nice to have your sections in your portfolio larger.. Perhaps when you add more content it will already do that for you but for now I feel like you can make them larger so it will look better in my eyes.

**Comment by tmzelaya** [comment]
That would certainly be a good idea if I intended to keep the "make everything disappear except this section" feature we were required to implement for the nav. But I do not plan on keeping that, so I'll leave the sections as is. Better than making them bigger now and smaller again later!
